import type { RouterMetaType } from "./routes.type";

const routerMeta: RouterMetaType = {
    HomePage: {
        name: "Home",
        path: "/",
        feature: "home",
        site: "public",
        page: "HomePage",
        file: "HomePage",
        requiresLayout: false,
        isAdmin: false,
    },
    LoginPage: {
        name: "Login",
        path: "/login",
        feature: "auth",
        site: "public",
        page: "LoginPage",
        file: "LoginPage",
        requiresLayout: false,
        isAdmin: false,
    },
    RegisterPage: {
        name: "Register",
        path: "/register",
        feature: "auth",
        site: "public",
        page: "RegisterPage",
        file: "RegisterPage",
        requiresLayout: false,
        isAdmin: false,
    },
    ProfilePage: {
        name: "Profile",
        path: "/profile",
        feature: "profile",
        site: "private",
        page: "ProfilePage",
        file: "ProfilePage",
        requiresLayout: true,
        isAdmin: false,
    },
    OnboardingPage: {
        name: "Onboarding",
        path: "/onboarding",
        feature: "onboarding",
        site: "private",
        page: "OnboardingPage",
        file: "OnboardingPage",
        requiresLayout: true,
        isAdmin: false,
    },
    DashboardPage: {
        name: "Dashboard",
        path: "/dashboard",
        feature: "dashboard",
        site: "private",
        page: "DashboardPage",
        file: "DashboardPage",
        requiresLayout: true,
        isAdmin: false,
    },
    ActivityPage: {
        name: "Activity",
        path: "/activity",
        feature: "activity",
        site: "private",
        page: "ActivityPage",
        file: "ActivityPage",
        requiresLayout: true,
        isAdmin: false,
    },
    FoodPage: {
        name: "Food",
        path: "/nutrition",
        feature: "food",
        site: "private",
        page: "FoodPage",
        file: "FoodPage",
        requiresLayout: true,
        isAdmin: false,
    },
    NotFoundPage: {
        name: "Not Found",
        path: "*",
        feature: "not-found",
        site: "public",
        page: "NotFoundPage",
        file: "NotFoundPage",
        requiresLayout: false,
        isAdmin: false,
    }
}

export default routerMeta;